name: Build using CMake
on: [push, pull_request, workflow_dispatch]

env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  # Windows-mingw-w64-gcc
  # =====================
  windows-mingw-w64-gcc:
    name: 🏁 Windows.mingw-w64.gcc
    runs-on: windows-2019

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        branch: [master]

    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          pacboy: >-
            git
            toolchain:p
            python-pip:p
            

      - name: add scons-compiledb
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version

      - name: Get Godot ref
        id: get-godot-ref
        run: |
          echo "godotref=$(git ls-remote https://github.com/godotengine/godot.git ${{ matrix.branch }} | awk '{print $1}')" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cache-godot
        with:
          path: |
            bin
            ext/api-dump
          key: Godot-${{ matrix.branch }}-${{ runner.os }}-${{ steps.get-godot-ref.outputs.godotref }}

      - name: Retrieve Godot.exe
        if: steps.cache-godot.outputs.cache-hit != 'true'
        uses: dsnopek/action-download-artifact@1322f74e2dac9feed2ee76a32d9ae1ca3b4cf4e9
        with:
          repo: godotengine/godot
          branch: master
          event: push
          workflow: windows_builds.yml
          workflow_conclusion: success
          name: windows-editor
          search_artifacts: true
          check_artifacts: true
          ensure_latest: true
          path: bin

      - name: give godot executable permissions
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          chmod +x ./bin/godot.windows.editor.x86_64.exe

      - name: Godot.exe Info Dump
        run: ./bin/godot.windows.editor.x86_64.exe --headless --script pre-build.gd

      - name: Godot.exe API Dump
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          mkdir -p ext/api-dump
          cd ext/api-dump
          ../../bin/godot.windows.editor.x86_64.exe  --headless --dump-gdextension-interface --dump-extension-api --quit

      - name: Get godot-cpp ref
        id: get-godot-cpp-ref
        run: |
          echo "godotcppref=$(git ls-remote https://github.com/godotengine/godot-cpp.git ${{ matrix.branch }} | awk '{print $1}')" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cache-godot-cpp
        with:
          path: ext/godot-cpp
          key: godot-cpp-${{ matrix.branch }}-${{ steps.get-godot-cpp-ref.outputs.godotcppref }}

      - name: Clone godot-cpp to ext folder
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: git clone --depth 1 -b ${{ matrix.branch }} https://github.com/godotengine/godot-cpp.git ext/godot-cpp

      - name: Build with Scons
        run: scons platform=windows
#      # Cmake configure and build godot-cpp
#      - name: Configure godot-cpp
#        # FIXME this stage uses in-source build, because the test extension
#        # relies on it. In the future change this to allow out of source build.
#        run: >-
#          cmake
#          -DCMAKE_BUILD_TYPE=Release
#          -GNinja .
#      - name: Build godot-cpp
#        run: |
#          cmake -LH -B .
#          cmake --build . -j $(nproc)
#
#      # Configure and build test extension
#      - name: Configure godot-cpp/test
#        run: >-
#          cmake -B build-test -S test
#          -DCMAKE_BUILD_TYPE=Release
#          -DGODOT_HEADERS_PATH="./godot-headers"
#          -DCPP_BINDINGS_PATH="."
#          -GNinja .
#      - name: Build godot-cpp/test
#        run: |
#          cmake -B build-test -LH
#          cmake --build build-test -j $(nproc)

#       - name: Upload artifact
#          uses: actions/upload-artifact@v3
#          with:
#          name: ${{ matrix.platforms.artifact-name }}-${{ matrix.builder.name }}
#          path: ${{ matrix.builder.artifact-dir}}${{ matrix.platforms.artifact-path }}
#          if-no-files-found: error